---
- name: create keyfile
  command: "openssl rand -base64 741 > {{mongo_keyfile}}"

- name: start mongodb
  command: "{{mongo_instance_dir}}/startMongo.sh"

- name: start replicaset
  command: "{{mongo_scripts_dir}}/initiateRepSet.sh"

- name: create admin user
  command: "{{mongo_scripts_dir}}/createAdminUser.sh"
