#!/bin/bash

CONFIGFILE="{{mongo_configfile}}"
OPTIONS=" --config $CONFIGFILE"

PIDFILE=`ps -fe | grep "$CONFIGFILE" | grep -v grep | tr -s " "|cut -d" " -f2`
mongod=/mongodb/bin/mongod

MONGO_USER={{mongo_user}}
MONGO_GROUP={{mongo_group}}

start()
{
  echo -n $"Starting mongod: "
  su "$MONGO_USER" -c "$mongod $OPTIONS"
}

stop()
{
  echo -n $"Stopping mongod: "
  $mongod --shutdown $OPTIONS
}

restart () {
        stop
        start
}

ulimit -n 12000
RETVAL=0

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload|force-reload)
    restart
    ;;
  status)
    status $mongod
    RETVAL=$?
    ;;
  *)
    echo "Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
    RETVAL=1
esac

exit $RETVAL
